Issue #5
kysect/github-activity-analyzer pull request #11
Opened 2021-03-31 14:29 UTC by TomGnill

2021-03-31 17:51 UTC, FrediKats requested changes

2021-03-31 17:51 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Group/Student.cs
> +            set => TotalContributions = ActivityInfo.Total;
Это ж рекурсия) Оно умрет. Тут не нужен сетер.

2021-03-31 17:51 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Group/Student.cs
> +            ActivityInfo = newProvider.GetActivityInfo(username).Result;
Лучше не делать в конструкторе. Лучше обновлять отдельно.

2021-03-31 17:51 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Group/StudyGroup.cs
> +            get => (from student in Students select student.TotalContributions).ToArray().Sum();
И опять, не стоит использовать этот синтаксис. Лучше на экстеншен методах.

2021-03-31 17:51 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Group/StudyGroup.cs
> +            private set => TotalContributions = (from student in Students select student.TotalContributions).ToArray().Sum();
Рекурсия, умрет.

2021-03-31 17:51 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Group/StudyGroup.cs
> +            List<int> averegeInts = Students.Select(student => Convert.ToInt32(student.ActivityInfo.PerMonthActivity().Average(c => c.Count))).ToList();
Лучше возвращать тогда уж в даблах, а не кастить в инт.

2021-03-31 17:51 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Group/StudyGroup.cs
> +        }
А зачем отдельно делать MaxValue и GetMaxValueStudent? Я думаю их можно смерджить. + я бы добавил необязательные аргументы от и до.

2021-03-31 19:38 UTC, TomGnill commented
Выглядит очень больно, я сам себе хочу глаза выбить.

2021-03-31 21:08 UTC, FrediKats requested changes

2021-03-31 21:08 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Group/Student.cs
>              ActivityInfo = newProvider.GetActivityInfo(username).Result;
Все еще в конструкторе....

2021-03-31 21:08 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Group/Student.cs
> +            return (from days in ActivityInfo.Contributions where days.Date < to && days.Date > @from select days.Count).ToList().Average();
@ _ @

2021-03-31 21:08 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Group/StudyGroup.cs
> +                    Students.Select(k => k.ActivityInfo.GetActivityForPeriod(from.GetValueOrDefault(), to.GetValueOrDefault())).ToList().Min());
Даже не буду пытаться вникать, просто перепиши.

2021-03-31 21:08 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Group/StudyGroup.cs
> +            }
Почему просто мин тайм не взять?

2021-03-31 21:08 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Group/StudyGroup.cs
> +            return Students.Select(s => s.GetMovingAverage(from, to)).ToList().Average();
А зачем ToList, а потом Avg?

2021-03-31 22:58 UTC, TomGnill commented on Kysect.GithubActivityAnalyzer/Group/Student.cs
> +            return (from days in ActivityInfo.Contributions where days.Date < to && days.Date > @from select days.Count).ToList().Average();
Блин как на это реагировать?

2021-04-01 05:49 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Group/Student.cs
> +        private GithubActivityProvider newProvider = new GithubActivityProvider();
Ты все еще создаешь внутри студента провайдера. Ты все еще в конструкторе вычисления делаешь. В дальнейшем сюда сложно будет подложить кеш или пареллелить.

2021-04-01 05:50 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Group/StudyGroup.cs
> +            }
Зачем вообще этот код?

2021-04-01 05:51 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Group/StudyGroup.cs
> +                .ToList().Min();
Зачем ToList а потом Min?

2021-04-01 05:51 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Group/StudyGroup.cs
> +            return Students.FirstOrDefault(s => s.ActivityInfo.GetActivityForPeriod(from.GetValueOrDefault(), to.GetValueOrDefault()) == minValue);
Кажется, тту логично будет сделать OrderBy + First

2021-04-01 05:52 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Group/StudyGroup.cs
> +            return Students.Select(k => k.ActivityInfo.GetActivityForPeriod(from.GetValueOrDefault(), to.GetValueOrDefault())).ToList().Average();
Лучше переносы делать.

2021-04-01 10:30 UTC, TomGnill commented on Kysect.GithubActivityAnalyzer/Group/StudyGroup.cs
> +            }
я что-то видимо не понимаю, я его точно удалял

2021-04-01 10:32 UTC, TomGnill commented on Kysect.GithubActivityAnalyzer/Group/Student.cs
> +        private GithubActivityProvider newProvider = new GithubActivityProvider();
Я не очень понимаю как мне сделать этот момент правильно

2021-04-01 10:38 UTC, TomGnill commented on Kysect.GithubActivityAnalyzer/Group/StudyGroup.cs
> +            }
ладно, сейчас если опять появится эта параша, я не виноват

2021-04-01 10:40 UTC, TomGnill commented on Kysect.GithubActivityAnalyzer/Group/StudyGroup.cs
> +            return Students.FirstOrDefault(s => s.ActivityInfo.GetActivityForPeriod(from.GetValueOrDefault(), to.GetValueOrDefault()) == minValue);
Не вижу особой разницы.

2021-04-01 10:40 UTC, TomGnill commented on Kysect.GithubActivityAnalyzer/Group/StudyGroup.cs
> +            return Students.Select(k => k.ActivityInfo.GetActivityForPeriod(from.GetValueOrDefault(), to.GetValueOrDefault())).ToList().Average();
Можно конкретнее?

2021-04-01 11:52 UTC, FrediKats approved these changes

2021-04-01 11:52 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Group/StudyGroup.cs
> +                .OrderBy(k => k.ActivityInfo.GetActivityForPeriod(from.GetValueOrDefault(), to.GetValueOrDefault()))
А зачем тут вызов GetValueOrDefault?

2021-04-01 11:52 UTC, merged