Tom branch
kysect/github-activity-analyzer pull request #14
Opened 2021-04-02 14:51 UTC by TomGnill

2021-04-02 17:45 UTC, FrediKats requested changes

2021-04-02 17:45 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/DetailedStats/DetailedStats.cs
> +       }
Зачем вложенным типом делать?

2021-04-02 17:45 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/DetailedStats/DetailedStats.cs
> +       public DetailedStats(List<(string,string)> studentsList, GithubActivityProvider provider)//номер группы, гитхаб
Если ты оставил коммент - значит твой код не очевидный. Переписывай)

2021-04-02 17:45 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/DetailedStats/DetailedStats.cs
> +           }
Кажется, если метод GroupBy для этого.

2021-04-02 17:45 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/DetailedStats/DetailedStats.cs
> +       public List<GroupInfo> GetDetailedStat(DateTime inputDate)
Не очевидно, что это за аргумент.

2021-04-02 17:45 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/DetailedStats/DetailedStats.cs
> +               var pair = new GroupInfo(group.Value, new List<MonthlyStatistics>());
Нейминг

2021-04-02 17:45 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/DetailedStats/DetailedStats.cs
> +               while (to <= DateTime.Now)
А почему не for?

2021-04-02 17:45 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/DetailedStats/DetailedStats.cs
> +                    };
Этот класс должен быть неизменяемым и при создании сразу принимать все аргументы.

2021-04-02 17:45 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/DetailedStats/DetailedStats.cs
> +                    monthStat.AverageValue = monthStat.DetailedStat.Average(a => a.Item2);
А почему не сделать AverageValue  вычисляемым полем?

2021-04-02 17:45 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/DetailedStats/DetailedStats.cs
> +                    monthStat.Month = from.Month.ToString() +"."+ from.Year.ToString();
Это как-то не очень выглядит.

2021-04-02 21:55 UTC, TomGnill commented on Kysect.GithubActivityAnalyzer/DetailedStats/DetailedStats.cs
> +       public DetailedStats(List<(string,string)> studentsList, GithubActivityProvider provider)//номер группы, гитхаб
+

2021-04-02 22:06 UTC, TomGnill commented on Kysect.GithubActivityAnalyzer/DetailedStats/DetailedStats.cs
> +       }
Переделал в отдельный класс, бизнес-логика просчёта в конструкторе.

2021-04-02 22:09 UTC, TomGnill commented on Kysect.GithubActivityAnalyzer/DetailedStats/DetailedStats.cs
> +               while (to <= DateTime.Now)
for вместо foreach или вместо while

2021-04-03 11:24 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/DetailedStats/DetailedStats.cs
> +               while (to <= DateTime.Now)
while

2021-04-03 11:35 UTC, FrediKats requested changes

2021-04-03 11:35 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/DetailedStats/DetailedStats.cs
> +           foreach (var pair in studentInfos)//убрать колхоз
Комменты убрать + не писать их на ру. Кодировка полетит.
+можно деконструктор заюзать.
+все еще можно через GroupBy сделать

2021-04-03 11:35 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/DetailedStats/MonthlyStatistics.cs
> +            Month = date.Month.ToString() + "." + date.Year.ToString();//сделать красиво :)
Почему просто не оставить дату?

2021-04-03 11:35 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/DetailedStats/MonthlyStatistics.cs
> +                MinValueStudent = (DetailedStat
Зачем скобочки? Поехала табуляция

2021-04-03 18:31 UTC, FrediKats approved these changes

2021-04-03 18:32 UTC, merged