GetActivityForPeriod+
kysect/github-activity-analyzer pull request #8
Opened 2021-03-23 10:23 UTC by TomGnill

2021-03-23 10:41 UTC, FrediKats requested changes

2021-03-23 10:41 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer.Sample/Program.cs
> +            */
Лучше экслюдить такие штуки, чтобы не ловить конфликты потом при мердже.

2021-03-23 10:41 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/GithubActivityProvider.cs
> +using System.Xml.Serialization;
А зачем тут xml?

2021-03-23 10:41 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/GithubActivityProvider.cs
> +            var jstring = JsonConvert.DeserializeObject<ActivityInfo>(response);
Нейминг.

2021-03-23 10:41 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/GithubActivityProvider.cs
> +            var contributionsList = jstring.Contributions.ToList();
А почему сразу не написать Contributions.Where( element => element.date < DateTime.Now)?

2021-03-23 10:41 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Models/ActivityInfo.cs
> +            List<int> arr = (from element in Contributions where element.date <= to && element.date >= @from select element.Count).ToList();
Не стоит использовать этот формат записи LINQ. Он менее очевидный, плохо расширяется.

2021-03-23 10:41 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Models/ActivityInfo.cs
> +            List<int> arr = (from element in Contributions where element.date <= to && element.date >= @from select element.Count).ToList();
Нейминг.

2021-03-23 10:41 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Models/ContributionsInfo.cs
> +        public DateTime date;
Кодстайл.

2021-03-23 10:41 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Models/ContributionsInfo.cs
> +            this.date = Convert.ToDateTime(date, CultureInfo.InvariantCulture);
Лучше использовать Parse, у конверта неочевидное поведение.

2021-03-23 10:41 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Properties/launchSettings.json
> +}
Это что?

2021-03-23 10:41 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Models/ContributionsInfo.cs
>          public string Date { get; set; }
Возможно, хорошим вариантом будет сделать проперти DateAsString и Date. Почитай как с помощью атрибутов мапить поля на имена из json.

2021-03-23 10:47 UTC, TomGnill commented on Kysect.GithubActivityAnalyzer/GithubActivityProvider.cs
> +using System.Xml.Serialization;
автоматом добавилось.

2021-03-23 10:48 UTC, TomGnill commented on Kysect.GithubActivityAnalyzer.Sample/Program.cs
> +            */
да я бы её удалил всё равно, тк перед тем как мёрджить ещё есть что поделать наверное. Например data сделать readonly

2021-03-23 10:50 UTC, TomGnill commented on Kysect.GithubActivityAnalyzer/Models/ContributionsInfo.cs
>          public string Date { get; set; }
я вот пытался вчера это найти, и как-то поиграться с свойствами, но не вышло

2021-03-23 11:14 UTC, TomGnill commented on Kysect.GithubActivityAnalyzer/Models/ActivityInfo.cs
> +            List<int> arr = (from element in Contributions where element.date <= to && element.date >= @from select element.Count).ToList();
могу только в foreach переделать.

2021-03-31 10:21 UTC, FrediKats requested changes

2021-03-31 10:21 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/GithubActivityProvider.cs
> +            activityInfo.Contributions = contributionsList.ToArray();
Кажется, можно вместо ToList поставить ToArray и убрать лишнюю переменную сразу выставляя в activityInfo.Contributions.

2021-03-31 10:21 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Models/ActivityInfo.cs
> +            List<int> elements = (from element in Contributions where element.Date <= to && element.Date >= @from select element.Count).ToList();
Разве это нельзя переписать на Contributions.Where().Select(e => e.Count).Sum()?

2021-03-31 10:21 UTC, FrediKats commented on Kysect.GithubActivityAnalyzer/Models/ContributionsInfo.cs
> +        public string DateAsString { get; set; }
Это же не будет работать. У тебя данные исходно прилетают странной строкой в поле Date. Протестируй после своих изменений, что результат с апи приходит и парсится.

2021-03-31 10:37 UTC, FrediKats approved these changes

2021-03-31 10:37 UTC, merged